plugins { id 'com.android.application' }

android {
    namespace 'io.github.storageisolation.visibilityfix'
    compileSdk 35
    defaultConfig {
        applicationId 'io.github.storageisolation.visibilityfix'
        minSdk 30
        targetSdk 28
        versionCode 17
        versionName '0.17-api102-dynamic-uid'
    }
}

dependencies { compileOnly 'io.github.libxposed:api:102.0.0' }
